Repository tarkalabs/tarka-ui-kit-android, pull requests merged in 2024-01, with the labels that each got.

#171 Tui divider component is created
  .idea/androidTestResultsUserPreferences.xml
  tarkaui/build.gradle.kts
  tarkaui/src/androidTest/java/com/tarkalabs/uicomponents/TUIDividerTest.kt
  tarkaui/src/androidTest/java/com/tarkalabs/uicomponents/screenshots/TUIDividerScreenshotTest.kt
  tarkaui/src/main/java/com/tarkalabs/uicomponents/components/TUIAppTopBar.kt
  tarkaui/src/main/java/com/tarkalabs/uicomponents/components/TUIDivider.kt
  tarkaui/src/main/java/com/tarkalabs/uicomponents/components/TUIMobileButtonBlock.kt
  tarkaui/src/main/java/com/tarkalabs/uicomponents/components/TUIMobileOverlayHeader.kt
  tarkaui/src/main/java/com/tarkalabs/uicomponents/components/TUIMultiLevelSelectorHeader.kt
  tarkaui/src/main/java/com/tarkalabs/uicomponents/components/email/TUIEmailField.kt
Labels: Don't Merge

#178 enhancement : fie renaming for screenshot hot testing
  tarkaui/src/androidTest/java/com/tarkalabs/uicomponents/TUIAppTopBarTest.kt
  tarkaui/src/androidTest/java/com/tarkalabs/uicomponents/screenshots/TUIAppTopBarScreenShotTest.kt
  tarkaui/src/androidTest/java/com/tarkalabs/uicomponents/screenshots/TUIMediaThumbnailScreenShotTest.kt
  tarkaui/src/androidTest/java/com/tarkalabs/uicomponents/screenshots/TUIMobileOverlayFooterScreenShotTest.kt
  tarkaui/src/androidTest/java/com/tarkalabs/uicomponents/screenshots/TUIMobileOverlayHeaderScreenShotTest.kt
Labels: enhancement

#179 fix : Box introduced in NavButton for size matching
  tarkaui/src/main/java/com/tarkalabs/uicomponents/components/tab/TUIFloatingNavButton.kt
Labels: bug
