Repository tarkalabs/tarka-ui-kit-android, pull requests merged in 2024-03, with the labels that each got.

#207 Version bumped to 1.1.4
  tarka-ui/build.gradle.kts
Labels: version update

#211 Code Optimised in TUITextRow
  tarka-ui/build.gradle.kts
  tarka-ui/src/main/java/com/tarkalabs/tarkaui/components/TUITextRow.kt
Labels: enhancement

#213 fix: UI fixes in Component and Icon style added in Badge
  tarka-ui/build.gradle.kts
  tarka-ui/screenshots/debug/screenshots-default/com.tarkalabs.uicomponents.screenshots.TUIBadgeScreenShotTest__testBadgeWithCount_darkTheme_false.png
  tarka-ui/screenshots/debug/screenshots-default/com.tarkalabs.uicomponents.screenshots.TUIBadgeScreenShotTest__testBadgeWithCount_darkTheme_true.png
  tarka-ui/screenshots/debug/screenshots-default/com.tarkalabs.uicomponents.screenshots.TUIBadgeScreenShotTest__testBadgeWithIcon_darkTheme_false.png
  tarka-ui/screenshots/debug/screenshots-default/com.tarkalabs.uicomponents.screenshots.TUIBadgeScreenShotTest__testBadgeWithIcon_darkTheme_true.png
  tarka-ui/src/androidTest/java/com/tarkalabs/uicomponents/TUIBadgeTest.kt
  tarka-ui/src/androidTest/java/com/tarkalabs/uicomponents/TUIEmailFieldTest.kt
  tarka-ui/src/androidTest/java/com/tarkalabs/uicomponents/screenshots/TUIBadgeScreenShotTest.kt
  tarka-ui/src/main/java/com/tarkalabs/tarkaui/components/TUIChip.kt
  tarka-ui/src/main/java/com/tarkalabs/tarkaui/components/TUIMobileOverlayMenuItem.kt
  tarka-ui/src/main/java/com/tarkalabs/tarkaui/components/TUINavigationRows.kt
  tarka-ui/src/main/java/com/tarkalabs/tarkaui/components/TUITextRow.kt
  tarka-ui/src/main/java/com/tarkalabs/tarkaui/components/base/TUIBadge.kt
  tarka-ui/src/main/java/com/tarkalabs/tarkaui/components/card/TUISelectionCard.kt
Labels: bug

#215 Fixing the Border issue In TUI Chip + Fix SuggestionChip Color in Dark Theme + Fixed TUISearchBar height issue
  tarka-ui/build.gradle.kts
  tarka-ui/src/main/java/com/tarkalabs/tarkaui/components/TUIAppTopBar.kt
  tarka-ui/src/main/java/com/tarkalabs/tarkaui/components/TUIChip.kt
  tarka-ui/src/main/java/com/tarkalabs/tarkaui/components/TUISearchBar.kt
Labels: Don't Merge

#216 bug fix: Padding and Height issues in few components
  tarka-ui/build.gradle.kts
  tarka-ui/src/main/java/com/tarkalabs/tarkaui/components/TUIAppTopBar.kt
  tarka-ui/src/main/java/com/tarkalabs/tarkaui/components/base/TUIToggleRow.kt
  tarka-ui/src/main/java/com/tarkalabs/tarkaui/components/card/TUISelectionCard.kt
  tarka-ui/src/main/java/com/tarkalabs/tarkaui/components/email/TUIEmailField.kt
Labels: bug
